### PR TITLE
new question - single or double-quote question

### PR DESCRIPTION
**Pull request by Console-buche**
# What this PR is about?
Adding a new question : single or double quote

## if it is a new question for the website

> put here the question like: "Tab or Space"
"Single or Double-Quote"

> Upload a screenshot of the question taken from your localhost environment
image

> Add the label: `new question`

Your PR will be reviewed and our CI will run some tests and checks. If everything is fine, and the joke is fun, we will merge it and your question will be available on the website 🎉

---

## If it's a new feature

- Describe your feature. If it's an existing issue, add the link to the issue.
- Add the label `feature` or `improvement`.

### Tests

- [x] I have run the tests of the project. `nx affected --target=test `

### Clean Code

- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by bdebon** [comment]
Ahaha I like the images!
The only thing is the size of the images. I think we can compress them a little bit, why not convert them to webm. Usually next/image is supposed to do it by itself but since I don't use a vps, since the project is exported and then uploaded via scp to the website, I don't have the magic of image optimisation...
Actually one of the cool improvement to be made would be to find a solution for that by either creating a github action that compress the images before merging, or by finding anything else that could make sure that the image are not too big

**Comment by Console-buche** [comment]
> Ahaha I like the images! The only thing is the size of the images. I think we can compress them a little bit, why not convert them to webm. Usually next/image is supposed to do it by itself but since I don't use a vps, since the project is exported and then uploaded via scp to the website, I don't have the magic of image optimisation... Actually one of the cool improvement to be made would be to find a solution for that by either creating a github action that compress the images before merging, or by finding anything else that could make sure that the image are not too big

Oooh yep, of course, let me convert them to webp.
 
Also while I'm at it : unrelated but I don't seem to be able to edit labels ? (no gear icon)

**Comment by bdebon** [comment]
Congrats! First PR ever merged to the project! <3
Happy to have your profile picture on the list of contributors!

**Pull request merged**
