### PR TITLE
feat(question): add question about neovim and vscode

### PR DESCRIPTION
**Pull request by Kubessandra**
# What this PR is about?

## if it is a new question for the website

> put here the question like: "Tab or Space"

> Upload a screenshot of the question taken from your localhost environment

> Add the label: `new question`

New question: "Neovim or Vscode"

Screenshot 2022-10-24 at 21 48 46

Your PR will be reviewed and our CI will run some tests and checks. If everything is fine, and the joke is fun, we will merge it and your question will be available on the website 🎉

---

## If it's a new feature

- Describe your feature. If it's an existing issue, add the link to the issue.
- Add the label `feature` or `improvement`.

### Tests

- [x] I have run the tests of the project. `nx affected --target=test `

### Clean Code

- [x] I made sure the code is type safe (no any)

### CODE REVIEW

**Comment by ewencodes** [comment]
Hi,
You should write `Visual Studio Code` in the VSCode pic ? Or `VSCode` ?

**Comment by Kubessandra** [comment]
> Hi, You should write `Visual Studio Code` in the VSCode pic ? Or `VSCode` ?

I can but this is a logo from Google, so if you find a better one let's I can make the change 😀
I didn't found one with VSCode our Visual Studio Code

**Comment by ewencodes** [comment]
> I can but this is a logo from Google, so if you find a better one let's I can make the change 😀
I didn't found one with VSCode our Visual Studio Code

You can use this one ?
[https://www.stickpng.com/img/icons-logos-emojis/tech-companies/visual-studio-code-logo-landscape](https://www.stickpng.com/img/icons-logos-emojis/tech-companies/visual-studio-code-logo-landscape)

**Comment by Kubessandra** [comment]
> > I can but this is a logo from Google, so if you find a better one let's I can make the change 😀
> > I didn't found one with VSCode our Visual Studio Code
> 
> You can use this one ? https://www.stickpng.com/img/icons-logos-emojis/tech-companies/visual-studio-code-logo-landscape

I already did, but the quality was not really good 😕

**Pull request closed without merging**
